sudo: required
language: ruby
addons:
  chrome: stable
rvm:
  - 2.4
before_script:
  - bundle exec rake wax:lunr
  - bundle exec jekyll build
script:
  - bundle exec rake wax:test
after_success:
  - bundle exec rake wax:push:gh
branches:
  only:
  - master
git:
  depth: false
