sudo: required
language: ruby
addons:
  chrome: stable
rvm:
  - 2.4
before_install:
  - echo -e "machine github.com\n  login $ACCESS_TOKEN" >> ~/.netrc
  - git lfs pull
before_script:
  - bundle exec rake wax:lunr
  - bundle exec jekyll build
script:
  - bundle exec rake wax:test
git:
  depth: false
