title: Style Revolution
description: Journal des Dames et des Modes
baseurl: ''
url: ''

# build settings
theme: minima
permalink: pretty
collections_dir: collections
exclude: [Gemfile*, vendor, Rakefile, README*, spec]

# collection settings
collections:
  pages:
    output: true
  exhibits:
    output: true
    lunr_index:
      content: true
      fields: [title, author]
  plates:
    output: true
    keep_order: true
    source: plates.csv
    layout: plate-page
    lunr_index:
      content: false
      fields: [title, _date, caption, translation, keywords, pid]

# search tests
quoll:
  full:
    page: search
    terms: [turban, cheveux, crêpe, rose]

# js dependencies
js:
  jquery:
    version: 3.2.1
    cdn: https://code.jquery.com/jquery-3.2.1.min.js
  elasticlunr:
    version: 0.9.6
    cdn: https://cdnjs.cloudflare.com/ajax/libs/elasticlunr/0.9.6/elasticlunr.min.js
  openseadragon:
    version: 2.3.1
    cdn: https://cdnjs.cloudflare.com/ajax/libs/openseadragon/2.3.1/openseadragon.min.js

webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
